[VL-61] Strip null fields
pagopa/pn-local-emulator-poc pull request #26
Opened 2022-09-07 13:24 UTC by kin0992

This project's scope is to emulate the Piattaforma Notifiche (PN) software. Since PN does not include null fields (the object mapper used [has been instructed as follow](https://github.com/pagopa/pn-delivery/blob/803daa4e0dc135867b8f61d179cb45e7bc4edc1a/src/main/resources/application.properties#L37)), then the behavior of this tool must be the same, which means that we have to accept null values, but we have to ignore them.

#### List of Changes
Add a method that removes keys with a null value from a JSON.
It replicates what has been done into [io-ts-commons repository](https://github.com/pagopa/io-ts-commons/blob/622a7585b2e3f3bacf872f52c698bb41c7fb8992/src/types.ts#L128) changing the condition.

If necessary, we can evaluate making a PR to that repo as well and import the method from `io-ts-commons`.

#### Motivation and Context
A client may call PN (and as a consequence, may call this tool too) passing a JSON with `null` value of some keys (e.g. `{"a": 1, b: null}`).

#### Types of changes
- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2022-09-07 14:01 UTC, datalek reviewed
This change is breaking compatibility, so I'm not sure it is a chore

2022-09-07 14:17 UTC, kin0992 commented
> This change is breaking compatibility, so I'm not sure it is a chore

I agree with you, and I thought about it. The reason why I set it as a chore is that we haven't released anything at the moment (and I know this is a strong condition). But if you prefer to change to breaking change, it's ok for me too.

2022-09-08 08:47 UTC, datalek requested changes

2022-09-08 08:47 UTC, datalek commented on src/adapters/http/__tests__/Handler.test.ts
> +describe('withoutNullValues', () => {
```suggestion
describe('removeNullValues', () => {
```

2022-09-08 15:12 UTC, kin0992 commented on src/adapters/http/__tests__/Handler.test.ts
> +describe('withoutNullValues', () => {
Done, thanks!

2022-09-13 13:01 UTC, datalek approved these changes
💥

2022-09-13 13:03 UTC, merged